[profile.default]
solc_version = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aa6/=lib/account-abstraction/v0.6.0/contracts/",
    "@aa7/=lib/account-abstraction/v0.7.0/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true
multiline_func_header = "params_first"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
