[profile.default]
solc_version = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 999999
via_ir = true
bracket_spacing = true
remappings = [
    "@aa/=lib/account-abstraction/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
