[profile.default]
solc_version = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aa6=lib/0.6/account-abstraction/contracts",
    "@aa7=lib/0.7/account-abstraction/contracts",
    "lib/0.6/account-abstraction:@openzeppelin=lib/0.6/openzeppelin-contracts",
    "lib/0.7/account-abstraction:@openzeppelin=lib/0.7/openzeppelin-contracts",
    "@openzeppelin4=lib/0.6/openzeppelin-contracts",
    "@openzeppelin5=lib/0.7/openzeppelin-contracts",
]

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true
multiline_func_header = "params_first"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
