[profile.default]
solc_version = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aa=lib/account-abstraction",
    "@oz=lib/openzeppelin-contracts",
    "lib/account-abstraction/0.6:@openzeppelin=lib/openzeppelin-contracts/4.9",
    "lib/account-abstraction/0.7:@openzeppelin=lib/openzeppelin-contracts/5.0"
]

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true
multiline_func_header = "params_first"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
