version: "3.8"
services:
  geth_setup:
    image: ghcr.io/foundry-rs/foundry
    working_dir: /waallet-contract
    command: ./docker/testnet/geth_setup/entry.sh
    volumes:
      - ../../:/waallet-contract
    networks:
      - testnet-node

  rundler_setup:
    image: alpine:3
    command: /rundler_setup/entry.sh
    volumes:
      - ./rundler_setup:/rundler_setup
    networks:
      - testnet-node

networks:
  testnet-node:
    name: testnet
    external: true
