version: "3.8"
services:
  geth_setup:
    image: ghcr.io/foundry-rs/foundry
    working_dir: /waallet-contract
    command: ./docker/testnet/geth_setup/entry.sh
    environment:
      - PASSKEY_CREDENTIAL_ID=${PASSKEY_CREDENTIAL_ID}
      - PASSKEY_X=${PASSKEY_X}
      - PASSKEY_Y=${PASSKEY_Y}
    volumes:
      - ../../:/waallet-contract
    networks:
      - testnet

  rundler_setup:
    image: alpine:3
    command: /rundler_setup/entry.sh
    volumes:
      - ./rundler_setup:/rundler_setup
    networks:
      - testnet

networks:
  testnet:
    name: testnet
    external: true
