version: "3.8"
services:
  geth:
    image: ethereum/client-go:v1.10.26
    expose:
      - "8545"
    ports:
      - "8545:8545"
    command:
      - --datadir=/root/.ethereum
      - --keystore=/root/.ethereum/keystore
      - --unlock=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - --password=/root/.ethereum/keystore/password
      - --miner.gaslimit=12000000
      - --miner.etherbase=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - --http
      - --http.api=personal,eth,net,web3,debug,clique
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --ignore-legacy-receipts
      - --allow-insecure-unlock
      - --rpc.allow-unprotected-txs
      - --dev
      - --verbosity=2
      - --nodiscover
      - --maxpeers=0
      - --mine
      - --miner.threads=1
      - --networkid=1337
    volumes:
      - ./keystore:/root/.ethereum/keystore

  geth_setup:
    image: ghcr.io/foundry-rs/foundry:nightly-72e44fb87c38b2acfa2b0b136fc1bc833f71e674
    platform: linux/amd64
    working_dir: /waallet-contract
    depends_on:
      - geth
    command: ./docker/testnet/geth_setup/entry.sh
    environment:
      - PASSKEY_CREDENTIAL_ID=${PASSKEY_CREDENTIAL_ID}
      - PASSKEY_X=${PASSKEY_X}
      - PASSKEY_Y=${PASSKEY_Y}
    volumes:
      - ../../:/waallet-contract
      - ./script:/script

  rundler_v0_6:
    image: pilagod/rundler:v0.0
    ports:
      # RPC port
      - "3006:3000"
      # Metrics port
      - "8006:8080"
    depends_on:
      - geth
    environment:
      - RUST_LOG=debug
      - CHAIN_ID=1337
      - NODE_HTTP=http://geth:8545
      - BUILDER_MAX_BUNDLE_SIZE=1
      - BUILDER_PRIVATE_KEY=0x6abb89895f93b02c1b9470db0fa675297f6cca832a5fc66d5dfd7661a42b37be
      - ENTRY_POINTS=0x663F3ad617193148711d28f5334eE4Ed07016602
      - MIN_STAKE_VALUE=0
      - MIN_UNSTAKE_DELAY=0
      - RPC_API=eth,debug,rundler
      - RPC_TIMEOUT_SECONDS=600

  # KNOWN ISSUE:
  # * Estimate user operation gas with init code would cause no reason validation reverted.
  # rundler_v0_6:
  #   image: pilagod/rundler:v0.2
  #   command: node
  #   ports:
  #     # RPC port
  #     - "3006:3000"
  #     # Metrics port
  #     - "8006:8080"
  #   depends_on:
  #     - geth
  #     - geth_setup
  #   environment:
  #     - RUST_LOG=debug
  #     - ENTRY_POINT_V0_7_ENABLED=false
  #     - CHAIN_ID=1337
  #     - CHAIN_ENTRY_POINT_ADDRESS_V0_6=0x663F3ad617193148711d28f5334eE4Ed07016602
  #     - NODE_HTTP=http://geth:8545
  #     - BUILDER_MAX_BUNDLE_SIZE=1
  #     - BUILDER_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
  #     - MIN_STAKE_VALUE=0
  #     - MIN_UNSTAKE_DELAY=0
  #     - RPC_API=eth,debug,rundler
  #     - RPC_TIMEOUT_SECONDS=600

  rundler_v0_7:
    image: pilagod/rundler:v0.2
    command: node
    ports:
      # RPC port
      - "3007:3000"
      # Metrics port
      - "8007:8080"
    depends_on:
      - geth
      - geth_setup
    environment:
      - RUST_LOG=debug
      - ENTRY_POINT_V0_6_ENABLED=false
      - CHAIN_ID=1337
      - CHAIN_ENTRY_POINT_ADDRESS_V0_7=0x057ef64E23666F000b34aE31332854aCBd1c8544
      - NODE_HTTP=http://geth:8545
      - BUILDER_MAX_BUNDLE_SIZE=1
      - BUILDER_PRIVATE_KEY=0xf09bac41ec4a841e465210850ffdac37bd99dc5c0d99b8b52e3c3794db821ea6
      - MIN_STAKE_VALUE=0
      - MIN_UNSTAKE_DELAY=0
      - RPC_API=eth,debug,rundler
      - RPC_TIMEOUT_SECONDS=600

  rundler:
    image: pilagod/rundler-proxy
    depends_on:
      - rundler_v0_6
      - rundler_v0_7
    ports:
      - "3000:3000"
    environment:
      - RUNDLER_V0_6=http://rundler_v0_6:3000
      - RUNDLER_V0_7=http://rundler_v0_7:3000

  rundler_setup:
    image: alpine:3
    depends_on:
      - rundler_v0_6
      - rundler_v0_7
      - rundler
    command: /rundler_setup/entry.sh
    volumes:
      - ./rundler_setup:/rundler_setup
      - ./script:/script
